{
    "name": "RMA - Return Merchandise Authorization (IAG)",
    "summary": "Unified RMA management with restocking fees, return shipping via Shippo, "
               "and full sales order integration",
    "version": "19.0.1.0.0",
    "category": "RMA",
    "website": "https://www.iagperformance.com",
    "author": "IAG Performance",
    "license": "AGPL-3",
    "depends": [
        "stock_account",
        "sale",
        "sale_stock",
        "stock_delivery",
        "mail",
        "delivery_shippo_iag",
    ],
    "data": [
        "security/rma_security.xml",
        "security/ir.model.access.csv",
        "data/mail_data.xml",
        "data/rma_void_reason_data.xml",
        "data/rma_operation_data.xml",
        "data/rma_reason_data.xml",
        "data/stock_data.xml",
        "data/rma_operation_update.xml",
        "report/report.xml",
        "views/report_rma.xml",
        "wizard/stock_picking_return_views.xml",
        "wizard/rma_delivery_views.xml",
        "wizard/rma_finalization_wizard_views.xml",
        "wizard/rma_void_wizard_views.xml",
        "wizard/rma_split_views.xml",
        "wizard/sale_order_rma_wizard_views.xml",
        "wizard/rma_return_shipping_wizard_views.xml",
        "wizard/rma_credit_note_shipping_wizard_views.xml",
        "wizard/shippo_rate_wizard_rma_views.xml",
        "views/res_partner_views.xml",
        "views/rma_finalization_views.xml",
        "views/rma_void_reason_views.xml",
        "views/rma_portal_templates.xml",
        "views/rma_team_views.xml",
        "views/rma_views.xml",
        "views/rma_tag_views.xml",
        "views/rma_reason_views.xml",
        "views/rma_operation.xml",
        "views/stock_picking_views.xml",
        "views/stock_warehouse_views.xml",
        "views/sale_views.xml",
        "views/sale_portal_template.xml",
        "views/account_move_views.xml",
        "views/res_config_settings_views.xml",
        "views/dashboard.xml",
        "data/rma_reporting_actions.xml",
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "/rma_odoo_19/static/src/scss/rma_sale.scss",
        ],
        "web.assets_frontend": [
            "/rma_odoo_19/static/src/js/rma_portal_form.esm.js",
            "/rma_odoo_19/static/src/scss/rma_sale.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "application": True,
    "installable": True,
}
