from . import account_move
from . import res_company
from . import res_config_settings
from . import res_partner
from . import res_users
from . import rma
from . import rma_kit_line
from . import rma_finalization
from . import rma_operation
from . import rma_reason
from . import rma_tag
from . import rma_team
from . import rma_void_reason
from . import sale
from . import stock_move
from . import stock_picking
from . import stock_warehouse
