{
    "name": "IAG Custom Settings",
    "version": "19.0.7.0.1",
    "summary": "Central IAG configuration (standalone app; not linked to Odoo Settings).",
    "category": "Sales/Sales",
    "author": "IAG",
    "license": "LGPL-3",
    "depends": [
        "sale",
        "l10n_us_check_printing",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/ckus_check_inherit.xml",
        "views/ckus_stub_inherit.xml",
        "views/custom_settings_views.xml",
        "views/sale_order_form_unlock_inherit.xml",
    ],
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
    "images": ["static/description/icon.png"],
}
